steps:
- name: gcr.io/cloud-builders/mvn:3.5.0-jdk-8
  args: ['clean', 'install', 'jib:build', '-Dimage=gcr.io/powerful-vine-329211/spring-batch-postgres-gcs-bq11']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'terrraform-spring-batch', '--image', 'gcr.io/powerful-vine-329211/spring-batch-postgres-gcs-bq11', '--region', 'us-central1','--allow-unauthenticated','--platform','managed']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'services','update-traffic','terrraform-spring-batch','--to-latest','--region', 'us-central1']  

options:
  logging: CLOUD_LOGGING_ONLY 
  
# - id: terraform-init
#   name: hashicorp/terraform:0.14.8
#   args:
#     - 'init'
#     - '-no-color'
#     - '-input=false'
#     - './'

# - id: terraform-plan
#   name: hashicorp/terraform:0.14.8
#   args:
#     - 'plan'
#     - '-no-color'
#     - '-input=false'
#     - './'

# - id: terraform-apply
#   name: hashicorp/terraform:0.14.8
#   args:
#     - 'apply'
#     - '-auto-approve'
#     - '-no-color'
#     - '-input=false'
#     - './'   
